import type {
  AggregationDocument,
  CustomerRecord,
  OrderRecord,
  ProductRecord,
  ProductTagRecord,
} from "./aggregation-types.js";

export const exampleOrders: readonly OrderRecord[] = [
  {
    id: "ord_1001",
    tenantId: "tenant_alpha",
    createdAt: "2026-04-01T09:10:00.000Z",
    status: "placed",
    customerId: "cust_1",
    productId: "prd_laptop_1",
    category: "laptops",
    salesChannel: "web",
    region: "IN",
    units: 1,
    totalInCents: 129_900,
  },
  {
    id: "ord_1002",
    tenantId: "tenant_alpha",
    createdAt: "2026-04-01T10:00:00.000Z",
    status: "placed",
    customerId: "cust_2",
    productId: "prd_audio_1",
    category: "audio",
    salesChannel: "mobile",
    region: "IN",
    units: 2,
    totalInCents: 39_800,
  },
  {
    id: "ord_1003",
    tenantId: "tenant_alpha",
    createdAt: "2026-04-01T11:00:00.000Z",
    status: "refunded",
    customerId: "cust_3",
    productId: "prd_audio_2",
    category: "audio",
    salesChannel: "web",
    region: "US",
    units: 1,
    totalInCents: 19_900,
  },
  {
    id: "ord_1004",
    tenantId: "tenant_alpha",
    createdAt: "2026-04-02T08:10:00.000Z",
    status: "placed",
    customerId: "cust_1",
    productId: "prd_accessory_1",
    category: "accessories",
    salesChannel: "partner",
    region: "EU",
    units: 3,
    totalInCents: 14_700,
  },
  {
    id: "ord_1005",
    tenantId: "tenant_alpha",
    createdAt: "2026-04-02T09:30:00.000Z",
    status: "placed",
    customerId: "cust_4",
    productId: "prd_laptop_1",
    category: "laptops",
    salesChannel: "web",
    region: "US",
    units: 1,
    totalInCents: 129_900,
  },
  {
    id: "ord_1006",
    tenantId: "tenant_alpha",
    createdAt: "2026-04-02T10:15:00.000Z",
    status: "placed",
    customerId: "cust_2",
    productId: "prd_audio_2",
    category: "audio",
    salesChannel: "mobile",
    region: "IN",
    units: 1,
    totalInCents: 24_900,
  },
  {
    id: "ord_1007",
    tenantId: "tenant_alpha",
    createdAt: "2026-04-03T07:45:00.000Z",
    status: "placed",
    customerId: "cust_5",
    productId: "prd_accessory_2",
    category: "accessories",
    salesChannel: "web",
    region: "IN",
    units: 4,
    totalInCents: 11_600,
  },
  {
    id: "ord_1008",
    tenantId: "tenant_alpha",
    createdAt: "2026-04-03T09:45:00.000Z",
    status: "cancelled",
    customerId: "cust_3",
    productId: "prd_audio_1",
    category: "audio",
    salesChannel: "partner",
    region: "EU",
    units: 1,
    totalInCents: 19_900,
  },
  {
    id: "ord_1009",
    tenantId: "tenant_beta",
    createdAt: "2026-04-01T09:30:00.000Z",
    status: "placed",
    customerId: "cust_6",
    productId: "prd_laptop_2",
    category: "laptops",
    salesChannel: "web",
    region: "US",
    units: 1,
    totalInCents: 159_900,
  },
  {
    id: "ord_1010",
    tenantId: "tenant_alpha",
    createdAt: "2026-04-03T12:20:00.000Z",
    status: "placed",
    customerId: "cust_4",
    productId: "prd_audio_1",
    category: "audio",
    salesChannel: "web",
    region: "EU",
    units: 2,
    totalInCents: 39_800,
  },
  {
    id: "ord_1011",
    tenantId: "tenant_alpha",
    createdAt: "2026-04-03T16:05:00.000Z",
    status: "placed",
    customerId: "cust_5",
    productId: "prd_accessory_1",
    category: "accessories",
    salesChannel: "mobile",
    region: "IN",
    units: 1,
    totalInCents: 4_900,
  },
  {
    id: "ord_1012",
    tenantId: "tenant_alpha",
    createdAt: "2026-04-04T09:00:00.000Z",
    status: "placed",
    customerId: "cust_2",
    productId: "prd_laptop_1",
    category: "laptops",
    salesChannel: "partner",
    region: "IN",
    units: 1,
    totalInCents: 129_900,
  },
];

export const exampleProducts: readonly ProductRecord[] = [
  { id: "prd_laptop_1", name: "Laptop Pro 14", category: "laptops", active: true },
  { id: "prd_laptop_2", name: "Laptop Ultra 16", category: "laptops", active: true },
  { id: "prd_audio_1", name: "Studio Headphones", category: "audio", active: true },
  { id: "prd_audio_2", name: "Conference Speaker", category: "audio", active: true },
  { id: "prd_accessory_1", name: "USB-C Dock", category: "accessories", active: true },
  { id: "prd_accessory_2", name: "Wireless Mouse", category: "accessories", active: true },
];

export const exampleCustomers: readonly CustomerRecord[] = [
  { id: "cust_1", tenantId: "tenant_alpha", tier: "enterprise" },
  { id: "cust_2", tenantId: "tenant_alpha", tier: "gold" },
  { id: "cust_3", tenantId: "tenant_alpha", tier: "standard" },
  { id: "cust_4", tenantId: "tenant_alpha", tier: "gold" },
  { id: "cust_5", tenantId: "tenant_alpha", tier: "enterprise" },
  { id: "cust_6", tenantId: "tenant_beta", tier: "enterprise" },
];

export const exampleProductTags: readonly ProductTagRecord[] = [
  { productId: "prd_laptop_1", tag: "premium" },
  { productId: "prd_laptop_1", tag: "remote-work" },
  { productId: "prd_audio_1", tag: "audio" },
  { productId: "prd_audio_1", tag: "best-seller" },
  { productId: "prd_audio_2", tag: "meeting-room" },
  { productId: "prd_accessory_1", tag: "desk-setup" },
  { productId: "prd_accessory_2", tag: "portable" },
  { productId: "prd_accessory_2", tag: "entry-level" },
];

export function toDocuments<T extends Record<string, unknown>>(rows: readonly T[]): readonly AggregationDocument[] {
  return rows.map((row) => ({ ...row }));
}

export const materializedRevenueByCategory = [
  {
    tenantId: "tenant_alpha",
    category: "laptops",
    revenueInCents: 389_700,
    orderCount: 3,
  },
  {
    tenantId: "tenant_alpha",
    category: "audio",
    revenueInCents: 104_500,
    orderCount: 3,
  },
  {
    tenantId: "tenant_alpha",
    category: "accessories",
    revenueInCents: 31_200,
    orderCount: 3,
  },
] as const;
