apiVersion: v1
kind: Secret
metadata:
  name: payments-api-secrets
  namespace: payments-prod
  labels:
    app.kubernetes.io/name: payments-api
type: Opaque
stringData:
  DATABASE_URL: replace-me
  JWT_PRIVATE_KEY: replace-me
