import type { MongoOrder } from "./mongo-types.js";

export const exampleOrders: readonly MongoOrder[] = [
  {
    _id: "ord_2001",
    tenantId: "tenant_alpha",
    userId: "usr_1",
    status: "placed",
    channel: "web",
    region: "IN",
    category: "laptops",
    totalInCents: 129_900,
    createdAt: "2026-04-01T09:00:00.000Z",
    tags: ["priority", "b2b"],
    shipping: { city: "Pune", priority: "express" },
    metrics: { retryCount: 0, viewCount: 8 },
  },
  {
    _id: "ord_2002",
    tenantId: "tenant_alpha",
    userId: "usr_2",
    status: "placed",
    channel: "mobile",
    region: "IN",
    category: "audio",
    totalInCents: 19_900,
    createdAt: "2026-04-01T10:00:00.000Z",
    tags: ["promo"],
    shipping: { city: "Mumbai", priority: "standard" },
    metrics: { retryCount: 1, viewCount: 12 },
  },
  {
    _id: "ord_2003",
    tenantId: "tenant_alpha",
    userId: "usr_3",
    status: "refunded",
    channel: "web",
    region: "US",
    category: "audio",
    totalInCents: 24_900,
    createdAt: "2026-04-01T11:00:00.000Z",
    tags: ["support"],
    shipping: { city: "Austin", priority: "standard" },
    metrics: { retryCount: 0, viewCount: 5 },
  },
  {
    _id: "ord_2004",
    tenantId: "tenant_alpha",
    userId: "usr_4",
    status: "placed",
    channel: "partner",
    region: "EU",
    category: "accessories",
    totalInCents: 4_900,
    createdAt: "2026-04-02T08:00:00.000Z",
    tags: ["bundle"],
    shipping: { city: "Berlin", priority: "standard" },
    metrics: { retryCount: 2, viewCount: 3 },
  },
  {
    _id: "ord_2005",
    tenantId: "tenant_alpha",
    userId: "usr_1",
    status: "cancelled",
    channel: "web",
    region: "IN",
    category: "audio",
    totalInCents: 39_800,
    createdAt: "2026-04-02T09:15:00.000Z",
    tags: ["manual-review"],
    shipping: { city: "Pune", priority: "express" },
    metrics: { retryCount: 3, viewCount: 7 },
  },
  {
    _id: "ord_2006",
    tenantId: "tenant_alpha",
    userId: "usr_5",
    status: "placed",
    channel: "mobile",
    region: "US",
    category: "laptops",
    totalInCents: 159_900,
    createdAt: "2026-04-03T09:45:00.000Z",
    tags: ["vip"],
    shipping: { city: "Seattle", priority: "express" },
    metrics: { retryCount: 0, viewCount: 15 },
  },
  {
    _id: "ord_2007",
    tenantId: "tenant_alpha",
    userId: "usr_2",
    status: "placed",
    channel: "web",
    region: "EU",
    category: "accessories",
    totalInCents: 11_600,
    createdAt: "2026-04-03T12:45:00.000Z",
    tags: ["gift"],
    shipping: { city: "Paris", priority: "standard" },
    metrics: { retryCount: 1, viewCount: 4 },
  },
  {
    _id: "ord_2008",
    tenantId: "tenant_beta",
    userId: "usr_6",
    status: "placed",
    channel: "web",
    region: "US",
    category: "laptops",
    totalInCents: 189_900,
    createdAt: "2026-04-03T14:10:00.000Z",
    tags: ["enterprise"],
    shipping: { city: "Chicago", priority: "express" },
    metrics: { retryCount: 0, viewCount: 20 },
  },
];
